version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ec2-db-quick-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ec2_db_quick_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ec2_db_quick_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: ec2-db-quick-app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db # Connect to the 'db' service
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
