version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - mysql-db
      - mssql-db
    # Environment variables for the app to find the databases
    environment:
      - PG_HOST=postgres-db
      - MYSQL_HOST=mysql-db
      - MSSQL_HOST=mssql-db

  postgres-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ec2_db_quick_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password # Not used by app
      - MYSQL_DATABASE=ec2_db_quick_test
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=aStrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  postgres-data:
  mysql-data:
  mssql-data:
