services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    environment:
      - PG_HOST=postgres-db
      - MYSQL_HOST=mysql-db

  postgres-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ec2_db_quick_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ec2_db_quick_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password # Not used by app
      - MYSQL_DATABASE=ec2_db_quick_test
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql_user", "--password=mysql_password"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  mysql-data:
